### ISSUE TITLE
long_memories_indexes[i]: attn IndexError: list index out of range

### ISSUE THREAD

**Issue by KnoDio** [Restricted-Memory/RMem#6]
I tried to run demo.py with my own dataset, and some of the datasets worked, but for some datasets I encountered the following error：
Traceback (most recent call last):
  File "C:\Users\13499\Documents\Matting\RMem\aot_plus\tools\demo.py", line 333, in <module>
    main()
  File "C:\Users\13499\Documents\Matting\RMem\aot_plus\tools\demo.py", line 329, in main
    demo(cfg)
  File "C:\Users\13499\Documents\Matting\RMem\aot_plus\tools\demo.py", line 247, in demo
    engine.update_memory(_pred_label)
  File "C:\Users\13499\Documents\Matting\RMem\aot_plus\networks\engines\aot_engine.py", line 721, in update_memory
    aot_engine.update_short_term_memory(separated_mask)
  File "C:\Users\13499\Documents\Matting\RMem\aot_plus\networks\engines\aot_engine.py", line 363, in update_short_term_memory
    self.AOT.LSTT.restrict_long_memories(
  File "C:\Users\13499\Documents\Matting\RMem\aot_plus\networks\layers\transformer.py", line 359, in restrict_long_memories
    long_memories_indexes[i]: attn
    ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
and i print the length of attn_weight and long_memories_indexes
len(attn_weight)=8, len(long_memories_indexes)=3
I would like to ask if there is any solution to this error，thanks

**Comment by junbao-zhou** [comment]
We didn't mean to use this demo.py, it was developed by AOT team. But now we modify it to make it compatible with our model, just run

```bash
python ./tools/demo.py --seq_name=10625_knead_dough
```

to test the demo.
